/******************************************************************************
** Copyright, 1999 - 2015, Intergraph Corporation. All rights reserved.
**
** CREATED: 2015-01-22
** PURPOSE: Versioning Header - This file is generated by versioner.py
**
******************************************************************************/

#define NCS_ECWJP2_VER_MAJOR 5
#define NCS_ECWJP2_VER_MINOR 2
#define NCS_ECWJP2_VER_SERVICE 1
#define NCS_ECWJP2_VER_BUILD 265
#define NCS_ECWJP2_VER_MAJOR_STR "5"
#define NCS_ECWJP2_VER_MINOR_STR "2"
#define NCS_ECWJP2_VER_SERVICE_STR "1"
#define NCS_ECWJP2_VER_BUILD_STR "265"
#define NCS_ECWJP2_VER NCS_ECWJP2_VER_MAJOR
#define NCS_ECWJP2_VERSION_NUMBER 5.2
#define NCS_ECWJP2_VERSION_STRING "5.2"
#define NCS_ECWJP2_FULL_VERSION_NUMBER 5.2.1.265
#define NCS_ECWJP2_FULL_VERSION_STRING "5,2,1,265\0"
#define NCS_ECWJP2_FULL_VERSION_STRING_NO_NULL "5,2,1,265"
#define NCS_ECWJP2_FULL_VERSION_STRING_DOT_DEL "5.2.1.265"
