#!/bin/sh
#
# This little script builds and installs the GDAL ECW plugin.
#
# You need to pre-build and install the ECW SDK 3.3+ in a suitable path
# (e.g. /usr/local/ECW3.3) and pass that path as an argument to this
# script. 
#
# Copyright (C) 2008 Francesco P. Lovergine <frankie@debian.org>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2, 
# as published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA
#

VERSION=1.10.0
PLUGINDIR=/usr/lib/gdalplugins/1.10
TARBALL=/usr/src/libgdal-ecw-$VERSION.tar.gz

if [ `id -u` -ne 0 ]; then
	echo "Run this script as root"
	exit 5
fi

if [ $# -ne 1 ]; then
	echo "usage: $0 /path/to/ecw/sdk/installation"
	exit 1
fi

if [ ! -f $TARBALL ]; then
	echo "missing source $TARBALL"
	exit 4
fi

ECWSDK=$1

if [ ! -d "$ECWSDK" ]; then
	echo "$ECWSDK does not exist or is not a directory"
	exit 2
fi

BUILDDIR=`mktemp -d /tmp/gdal-ecw-build.XXXXXX`

echo "Extracting GDAL/ECW tarball" 
tar xzf $TARBALL -C $BUILDDIR

echo "Building GDAL/ECW plugin"
( cd $BUILDDIR/libgdal-ecw-$VERSION && \
 	sh ./configure --with-ecw=$ECWSDK --with-autoload=$PLUGINDIR&& \
	make && \
       make plugin && \
	make install && chown root:root $PLUGINDIR/gdal_ECW_JP2ECW.so && chmod 0644 $PLUGINDIR/gdal_ECW_JP2ECW.so )

rm -rf $BUILDDIR
